-- Action bindings — generated by Ansible from the workstation_actions registry.
-- Do not edit manually; changes will be overwritten on next bootstrap.
-- To change bindings, edit shared/roles/keyboard/defaults/main.yml.

-- Open app launcher
hs.hotkey.bind({ "ctrl", "shift" }, "space", function()
  hs.execute("open raycast://", true)
end)

-- Clipboard history
hs.hotkey.bind({ "cmd", "shift" }, "v", function()
  hs.execute("open raycast://extensions/raycast/clipboard-history/clipboard-history", true)
end)

-- Emoji picker
hs.hotkey.bind({ "alt" }, ".", function()
  hs.execute("open raycast://extensions/raycast/emoji-symbols/search-emoji-symbols", true)
end)

-- Screenshot selected region
hs.hotkey.bind({ "cmd", "shift" }, "4", function()
  hs.execute("open \"cleanshot://capture-area\"", true)
end)

-- Screenshot full screen
hs.hotkey.bind({ "cmd", "shift" }, "3", function()
  hs.eventtap.keyStroke({"cmd", "shift"}, "3")
end)

-- Tile window left half
hs.hotkey.bind({ "ctrl", "alt" }, "left", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToUnit(hs.layout.left50) end

end)

-- Tile window right half
hs.hotkey.bind({ "ctrl", "alt" }, "right", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToUnit(hs.layout.right50) end

end)

-- Maximize window
hs.hotkey.bind({ "ctrl", "alt" }, "up", function()
  local win = hs.window.focusedWindow()
  if win then win:maximize() end

end)

-- Restore window
hs.hotkey.bind({ "ctrl", "alt" }, "down", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToUnit({x = 0.1, y = 0.1, w = 0.8, h = 0.8}) end

end)

-- Move window to next monitor
hs.hotkey.bind({ "ctrl", "alt", "cmd" }, "right", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToScreen(win:screen():next()) end

end)

-- Move window to previous monitor
hs.hotkey.bind({ "ctrl", "alt", "cmd" }, "left", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToScreen(win:screen():previous()) end

end)

-- Toggle fullscreen
hs.hotkey.bind({ "ctrl", "cmd", "alt" }, "f", function()
  local win = hs.window.focusedWindow()
  if win then win:setFullScreen(not win:isFullScreen()) end

end)

-- Center window at two-thirds width
hs.hotkey.bind({ "ctrl", "cmd", "alt" }, "space", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToUnit({x = 1/6, y = 0, w = 2/3, h = 1}) end

end)

-- Tile window left third
hs.hotkey.bind({ "ctrl", "alt" }, "d", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToUnit({x = 0, y = 0, w = 1/3, h = 1}) end

end)

-- Tile window center third
hs.hotkey.bind({ "ctrl", "alt" }, "f", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToUnit({x = 1/3, y = 0, w = 1/3, h = 1}) end

end)

-- Tile window right third
hs.hotkey.bind({ "ctrl", "alt" }, "g", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToUnit({x = 2/3, y = 0, w = 1/3, h = 1}) end

end)

-- Tile window left two-thirds
hs.hotkey.bind({ "ctrl", "alt" }, "e", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToUnit({x = 0, y = 0, w = 2/3, h = 1}) end

end)

-- Tile window right two-thirds
hs.hotkey.bind({ "ctrl", "alt" }, "r", function()
  local win = hs.window.focusedWindow()
  if win then win:moveToUnit({x = 1/3, y = 0, w = 2/3, h = 1}) end

end)

-- Hide window
hs.hotkey.bind({ "cmd" }, "h", function()
  local app = hs.application.frontmostApplication()
  if app then app:hide() end

end)

