-- Hammerspoon configuration.
-- Managed by iac-daily-driver-environments.
-- This file is Stow-managed. actions.lua is generated by Ansible template.

-- Launch Hammerspoon on login and show menu-bar icon.
hs.autoLaunch(true)
hs.menuIcon(true)

-- Enable IPC (CLI `hs` command and hammerspoon:// URL scheme).
require("hs.ipc")

-- Auto-reload when any .lua file changes.
local configWatcher = configWatcher  -- luacheck: ignore (suppress unused warning)
configWatcher = hs.pathwatcher.new(hs.configdir, function(files)
  for _, file in pairs(files) do
    if file:sub(-4) == ".lua" then
      hs.reload()
      return
    end
  end
end):start()

-- Load action bindings (generated from the action registry).
require("actions")

hs.notify.new({ title = "Hammerspoon", informativeText = "Config loaded" }):send()
