-- Hammerspoon configuration.
-- Managed by iac-daily-driver-environments.
-- This file is Stow-managed. actions.lua is generated by Ansible template.

-- Auto-reload when any .lua file changes.
local configWatcher = configWatcher  -- luacheck: ignore (suppress unused warning)
configWatcher = hs.pathwatcher.new(hs.configdir, function(files)
  for _, file in pairs(files) do
    if file:sub(-4) == ".lua" then
      hs.reload()
      return
    end
  end
end):start()

-- Load action bindings (generated from the action registry).
require("actions")

hs.notify.new({ title = "Hammerspoon", informativeText = "Config loaded" }):send()
