---
- name: restart dock
  ansible.builtin.command: killall Dock
  failed_when: false

- name: restart finder
  ansible.builtin.command: killall Finder
  failed_when: false

- name: restart systemuiserver
  ansible.builtin.command: killall SystemUIServer
  failed_when: false

- name: restart iterm2
  ansible.builtin.debug:
    msg: "iTerm2 defaults applied. Restart iTerm2 to see changes."
