---
# Microsoft OneDrive cloud storage
- name: Install OneDrive (macOS)
  when: ansible_facts.os_family == "Darwin"
  community.general.homebrew_cask:
    name: onedrive
    state: present

- name: Install OneDrive (Debian)
  when: ansible_facts.os_family == "Debian"
  block:
    - name: Add abraunegg OneDrive PPA
      ansible.builtin.apt_repository:
        repo: ppa:yann1ck/onedrive
        filename: onedrive
        state: present
      become: true

    - name: Install OneDrive client
      ansible.builtin.apt:
        name: onedrive
        state: present
        update_cache: true
      become: true
