---
- name: "Phase 6: Bureau Veritas"
  hosts: localhost
  connection: local

  roles:
    - role: word
      tags: [word, bureau-veritas]

    - role: excel
      tags: [excel, bureau-veritas]

    - role: powerpoint
      tags: [powerpoint, bureau-veritas]

    - role: outlook
      tags: [outlook, bureau-veritas]

    - role: edge
      tags: [edge, bureau-veritas]

    - role: onedrive
      tags: [onedrive, bureau-veritas]

    - role: teams
      tags: [teams, bureau-veritas]
