---
# Firefox sub-task
- name: Install Firefox (macOS)
  when: ansible_facts.os_family == "Darwin"
  community.general.homebrew_cask:
    name: firefox
    state: present

- name: Install Firefox (Debian)
  when: ansible_facts.os_family == "Debian"
  block:
    - name: Verify Firefox is installed
      ansible.builtin.command: firefox --version
      register: firefox_check
      changed_when: false
      failed_when: false

    - name: Install Firefox if not present
      when: firefox_check.rc != 0
      ansible.builtin.apt:
        name: firefox
        state: present
      become: true
