---
# Microsoft Teams
- name: Install Teams (macOS)
  when: ansible_facts.os_family == "Darwin"
  community.general.homebrew_cask:
    name: microsoft-teams
    state: present

- name: Install Teams (Debian)
  when: ansible_facts.os_family == "Debian"
  block:
    - name: Check if teams-for-linux snap is installed
      ansible.builtin.command: snap list teams-for-linux
      register: _teams_check
      changed_when: false
      failed_when: false

    - name: Install teams-for-linux snap
      when: _teams_check.rc != 0
      community.general.snap:
        name: teams-for-linux
        state: present
      become: true
