---
# delta (git diff pager) sub-task
- name: Install delta (macOS)
  when: ansible_os_family == "Darwin"
  community.general.homebrew:
    name: delta
    state: present

- name: Install delta (Debian)
  when: ansible_os_family == "Debian"
  ansible.builtin.shell: |
    DELTA_VERSION=$(curl -s https://api.github.com/repos/dandavison/delta/releases/latest | grep -Po '"tag_name": "\K[^"]*')
    curl -fsSL "https://github.com/dandavison/delta/releases/latest/download/git-delta_${DELTA_VERSION}_amd64.deb" -o /tmp/delta.deb
    dpkg -i /tmp/delta.deb
    rm -f /tmp/delta.deb
  args:
    creates: /usr/bin/delta
  become: true
