---
# Linux: RustDesk + Remmina

- name: Install RustDesk
  ansible.builtin.include_tasks: rustdesk.yml
  tags: [rustdesk]

- name: Install Remmina
  ansible.builtin.include_tasks: remmina.yml
  tags: [remmina]
