---
# macOS: VPN apps

- name: Install Tailscale
  community.general.homebrew_cask:
    name: tailscale
    state: present

- name: Install Surfshark
  community.general.homebrew_cask:
    name: surfshark
    state: present
