---
- name: Install zsh via Homebrew
  community.general.homebrew:
    name: zsh
    state: present

- name: Set zsh path fact
  ansible.builtin.set_fact:
    zsh_path: /opt/homebrew/bin/zsh

- name: Add Homebrew zsh to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/zsh
    state: present
  become: true
